server:
  port: ${port:4001}

spring:
  application:
    name: server-resource
#  profiles:
#    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ENC(vcVNyPrk4crUSc4IWgwO8Q==)
    password: ENC(vcVNyPrk4crUSc4IWgwO8Q==）
    virtual-host: /

# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id  # 雪花算法
    banner: false


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: superhire
