server:
  port: ${port:7001}

spring:
  application:
    name: user-service
#  profiles:
#    active: dev
# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id  # 雪花算法
      update-strategy: not_empty  # 字段更新策略 （空值不更新）
    banner: false



seata:
  enabled: true
  tx-service-group: hire_tx_group
  service:
    vgroup-mapping:
      hire_tx_group: SEATA_GROUP
    grouplist:
      SEATA_GROUP: 127.0.0.1:18091
  config:
    nacos:
      server-addr: 127.0.0.1:18848
      username:
      password:
  registry:
    nacos:
      server-addr: 127.0.0.1:18848
      username:
      password: