server:
  port: ${port:8111}

spring:
  application:
    name: auth-service
#  profiles:
#    active: dev
# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id  # 雪花算法
    banner: false


redis:
  host: ${redis.host:127.0.0.1}
  port: ${redis.port:16379}
  database: ${redis.database:0}
