server:
  port: ${port:8111}

spring:
  application:
    name: auth-service
  redis:
    host: 172.23.132.99
    port: 16379
    database: 0
#  profiles:
#    active: dev
# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id  # 雪花算法
    banner: false



