spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                   # 开启从注册中心动态创建路由的功能
      routes:
        - id: userRouter
          uri: lb://user-service           # lb://表示开启负载均衡 后面根据注册实际名称，没有指定的话就是application.name
          predicates:
            - Path=/userinfo/**,/admininfo/**

        - id: companyRouter
          uri: lb://company-service
          predicates:
            - Path=/company/**

        - id: authRouter
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/passport/**,/saas/**,/admin/**

        - id: resourceRouter
          uri: lb://server-resource
          predicates:
            - Path=/resource/**,/industry/**,/dataDict/**,/jobType/**,/sys/**

        - id: workRouter
          uri: lb://work-service
          predicates:
            - Path=/resume/**,/job/**

        - id: fileRouter
          uri: lb://file-service
          predicates:
            - Path=/file/**,/static/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true


    loadbalancer:       #开启基于nacos规则的负载均衡
      nacos:
        enabled: true