server:
  port: ${port:5001}

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 500kb  # 文件上传大小的限制，设置的最大值，不能超过，否则会报错
      max-request-size: 500kb  # 文件最大请求限制，用于批量上传

#  profiles:
#    active: dev

# 配置日志级别
logging:
  level:
    root: info
